<script setup>
import { computed, reactive } from 'vue'
import { activePerson, store, uid } from '../lib/store'
import { euro, round } from '../lib/calculations'
const states = ['Baden-Württemberg','Bayern','Berlin','Brandenburg','Bremen','Hamburg','Hessen','Mecklenburg-Vorpommern','Niedersachsen','Nordrhein-Westfalen','Rheinland-Pfalz','Saarland','Sachsen','Sachsen-Anhalt','Schleswig-Holstein','Thüringen']
const person = computed(() => activePerson())
const form = reactive({ helper: '', state: 'Baden-Württemberg', date: new Date().toISOString().slice(0,10), hours: 1, rate: 12.5, expenses: 0, source: 'relief', activity: 'Unterstützung im Haushalt', recognized: false })
const amount = computed(() => round(form.hours * form.rate + Number(form.expenses || 0)))
const entries = computed(() => store.neighborEntries.filter((entry) => entry.personId === person.value.id))
const total = computed(() => entries.value.reduce((sum, item) => sum + item.amount, 0))
function save() { store.neighborEntries.push({ id: uid('neighbor'), personId: person.value.id, ...JSON.parse(JSON.stringify(form)), amount: amount.value }); form.date = new Date().toISOString().slice(0,10) }
</script>
<template>
  <div class="section-heading"><div><p>Stunden, Kosten und Nachweise</p><h2>Nachbarschaftshilfe dokumentieren</h2></div><span class="law-badge neutral">Landesrecht beachten</span></div>
  <div class="metrics-grid three"><article class="metric-card accent"><span>Erfasste Kosten</span><strong>{{ euro(total) }}</strong><small>{{ entries.length }} Leistungen</small></article><article class="metric-card"><span>Monatlicher Entlastungsbetrag</span><strong>{{ euro(131) }}</strong><small>bei häuslicher Pflege</small></article><article class="metric-card"><span>Aktuelle Eingabe</span><strong>{{ euro(amount) }}</strong><small>{{ form.hours }} Stunden</small></article></div>
  <div class="calculator-layout balanced"><form class="panel form-grid" @submit.prevent="save"><h3 class="full">Leistung erfassen</h3><label>Helfer/in<input v-model.trim="form.helper" required placeholder="Name" /></label><label>Bundesland<select v-model="form.state"><option v-for="state in states" :key="state">{{ state }}</option></select></label><label>Datum<input v-model="form.date" type="date" required /></label><label>Tätigkeit<select v-model="form.activity"><option>Unterstützung im Haushalt</option><option>Begleitung außer Haus</option><option>Einkaufen und Besorgungen</option><option>Alltagsbegleitung</option><option>Sonstige Unterstützung</option></select></label><label>Stunden<input v-model.number="form.hours" type="number" min="0.25" step="0.25" required /></label><label>Stundensatz<div class="money-input"><span>€</span><input v-model.number="form.rate" type="number" min="0" step="0.01" required /></div></label><label>Auslagen<div class="money-input"><span>€</span><input v-model.number="form.expenses" type="number" min="0" step="0.01" /></div></label><label>Finanzierung<select v-model="form.source"><option value="relief">Entlastungsbetrag</option><option value="conversion">Umwandlungsanspruch</option></select></label><label class="check-card full"><input v-model="form.recognized" type="checkbox" required /><span><strong>Anerkennungsstatus geprüft</strong><small>Helfer/in oder Angebot erfüllt die Regeln des gewählten Bundeslands.</small></span></label><button class="button primary full">Leistung speichern · {{ euro(amount) }}</button></form>
    <aside class="panel"><p class="eyebrow">Wichtiger Hinweis</p><h3>Regeln unterscheiden sich je Bundesland</h3><p class="muted prose">Voraussetzungen, zulässige Tätigkeiten und Vergütung richten sich nach Landesrecht. Der Rechner dokumentiert Kosten; er bestätigt keine Erstattung durch die Pflegekasse.</p><div class="info-stack"><div><span>1</span><p><strong>Anerkennung prüfen</strong><br />Bei der zuständigen Landesstelle oder Pflegekasse.</p></div><div><span>2</span><p><strong>Nachweis führen</strong><br />Datum, Tätigkeit, Dauer und Betrag vollständig erfassen.</p></div><div><span>3</span><p><strong>Belege einreichen</strong><br />Abrechnung mit den erforderlichen Unterschriften senden.</p></div></div><button class="button ghost full-width" @click="print()">Monatsnachweis drucken</button></aside>
  </div>
  <article class="panel"><div class="panel-heading"><h3>Leistungsnachweise</h3><span>{{ entries.length }} Einträge</span></div><div v-if="entries.length" class="table-wrap"><table><thead><tr><th>Datum</th><th>Helfer/in</th><th>Tätigkeit</th><th>Stunden</th><th>Betrag</th><th></th></tr></thead><tbody><tr v-for="entry in entries" :key="entry.id"><td>{{ entry.date }}</td><td>{{ entry.helper }}</td><td>{{ entry.activity }}</td><td>{{ entry.hours }}</td><td>{{ euro(entry.amount) }}</td><td><button class="text-danger" @click="store.neighborEntries.splice(store.neighborEntries.indexOf(entry),1)">Löschen</button></td></tr></tbody></table></div><div v-else class="empty compact"><span>◇</span><strong>Noch keine Leistungen</strong></div></article>
</template>
