<script setup>
import { computed, reactive } from 'vue'
import { activePerson, store, uid } from '../lib/store'
import { respiteCalculation, euro } from '../lib/calculations'
const person = computed(() => activePerson())
const form = reactive({ relation: 'other', fee: 0, travel: 0, incomeLoss: 0, sharedSpent: 0, days: 1, hourly: false, start: new Date().toISOString().slice(0,10), helper: '' })
const recordedSpent = computed(() => store.respiteEntries.filter((entry) => entry.personId === person.value.id).reduce((sum, entry) => sum + Number(entry.reimbursed || 0), 0))
const result = computed(() => respiteCalculation({ degree: person.value.degree, ...form, sharedSpent: recordedSpent.value + Number(form.sharedSpent || 0) }))
function save() { store.respiteEntries.push({ id: uid('respite'), personId: person.value.id, date: form.start, helper: form.helper || 'Ersatzpflegeperson', ...JSON.parse(JSON.stringify(form)), ...result.value }) }
</script>
<template>
  <div class="section-heading"><div><p>Erstattung und Pflegegeld im Blick</p><h2>Verhinderungspflege berechnen</h2></div><span class="law-badge">Regelstand ab 01.07.2025</span></div>
  <div class="calculator-layout balanced"><form class="panel form-grid" @submit.prevent="save"><h3 class="full">Einsatz erfassen</h3><label class="full">Ersatzpflegeperson<input v-model.trim="form.helper" placeholder="z. B. Alex Beispiel" /></label><label>Datum<input v-model="form.start" type="date" required /></label><label>Anzahl Tage<input v-model.number="form.days" type="number" min="1" max="56" required /></label><label class="full">Verhältnis<select v-model="form.relation"><option value="other">Sonstige oder erwerbsmäßige Ersatzpflege</option><option value="near">Bis 2. Grad verwandt/verschwägert oder gleicher Haushalt</option></select></label><label>Vergütung<div class="money-input"><span>€</span><input v-model.number="form.fee" type="number" min="0" step="0.01" /></div></label><label>Fahrtkosten<div class="money-input"><span>€</span><input v-model.number="form.travel" type="number" min="0" step="0.01" /></div></label><label>Verdienstausfall<div class="money-input"><span>€</span><input v-model.number="form.incomeLoss" type="number" min="0" step="0.01" /></div></label><label>Bereits gemeinschaftlich verbraucht<div class="money-input"><span>€</span><input v-model.number="form.sharedSpent" type="number" min="0" max="3539" step="0.01" /></div></label><label class="check-card full"><input v-model="form.hourly" type="checkbox" /><span><strong>Stundenweise Verhinderung</strong><small>Die Pflegeperson ist an jedem Tag weniger als 8 Stunden verhindert.</small></span></label><button class="button primary full">Abrechnung speichern</button></form>
    <aside class="panel result-panel"><p class="eyebrow">Voraussichtliche Erstattung</p><strong class="hero-number">{{ euro(result.reimbursed) }}</strong><dl class="result-list"><div><dt>Bereits hier erfasst</dt><dd>{{ euro(recordedSpent) }}</dd></div><div><dt>Verfügbarer Jahrestopf</dt><dd>{{ euro(result.available) }}</dd></div><div><dt>Anerkennungsfähige Kosten</dt><dd>{{ euro(result.eligible) }}</dd></div><div><dt>Eigenanteil</dt><dd>{{ euro(result.ownCost) }}</dd></div><div><dt>Verbleibendes Budget</dt><dd>{{ euro(result.remaining) }}</dd></div><div><dt>Kürzungstage</dt><dd>{{ result.reductionDays }}</dd></div><div><dt>Pflegegeldkürzung</dt><dd>{{ euro(result.cashReduction) }}</dd></div></dl><button class="button ghost full-width" @click="print()">Druckansicht</button><small class="legal-note">Die Pflegekasse entscheidet über die Anerkennung der eingereichten Aufwendungen.</small></aside>
  </div>
  <article v-if="store.respiteEntries.filter(e=>e.personId===person.id).length" class="panel"><div class="panel-heading"><h3>Gespeicherte Einsätze</h3></div><div class="table-wrap"><table><thead><tr><th>Datum</th><th>Ersatzpflegeperson</th><th>Erstattung</th><th>Rest</th></tr></thead><tbody><tr v-for="entry in store.respiteEntries.filter(e=>e.personId===person.id)" :key="entry.id"><td>{{ entry.date }}</td><td>{{ entry.helper }}</td><td>{{ euro(entry.reimbursed) }}</td><td>{{ euro(entry.remaining) }}</td></tr></tbody></table></div></article>
</template>
